language: node_js
node_js:
  - "iojs"
  - "7"
script:
  - echo "Deploying ListaZakupow"
install:
  - npm install -g firebase-tools
after success:
  - firebase deploy --projectId lista-zakupow-acd7a  --token "$FIREBASE_TOKEN"